name:                hecret-service
version:             0.1.0.0
github:              "zsedem/hecret-service"
license:             LGPL
author:              "Adam Oliver Zsigmond"
maintainer:          "zsedem@gmail.com"
copyright:           "2019 Adam Oliver Zsigmond"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zsedem/hecret-service>

dependencies:
- base >= 4.7 && < 5
- dbus


library:
  source-dirs: lib

executables:
  hecret-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hecret-service

tests:
  hecret-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hecret-service
